# Generated by Django 3.0.8 on 2020-07-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carteira', models.IntegerField()),
                ('dt_referencia', models.DateField()),
                ('nr_conta', models.IntegerField()),
                ('carteira', models.CharField(max_length=200)),
                ('faixa', models.CharField(max_length=200)),
                ('qtd_carteira', models.IntegerField()),
                ('vl_carteira', models.DecimalField(decimal_places=2, max_digits=18)),
                ('qtd_pagamentos', models.IntegerField()),
                ('vl_pago', models.DecimalField(decimal_places=2, max_digits=18)),
                ('qtd_pag_acordo', models.IntegerField()),
                ('pagamento_acordo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('qtd_colchao', models.IntegerField()),
                ('PagamentoColchao', models.DecimalField(decimal_places=2, max_digits=18)),
                ('qtd_espontaneo', models.IntegerField()),
                ('pagamento_espontaneo', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Discagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_campanha', models.IntegerField()),
                ('campanha', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('classificacao', models.CharField(max_length=150)),
                ('tabulacao', models.CharField(max_length=200)),
                ('faixa', models.CharField(max_length=200)),
                ('unic', models.IntegerField()),
                ('tentativas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_campanha', models.IntegerField()),
                ('mailing', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('recebido', models.IntegerField()),
                ('importado', models.IntegerField()),
                ('trabalhado', models.IntegerField()),
                ('campanha', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_campanha', models.IntegerField()),
                ('campanha', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('login', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('tempo', models.IntegerField()),
            ],
        ),
    ]
