# Generated by Django 3.0.8 on 2021-02-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_remove_user_following'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
